/**
* Aplication Charts generated by ChartJS
**/

var data = [
	{
		value: 30,
		color:"#F38630"
	},
	{
		value : 50,
		color : "#E0E4CC"
	},
	{
		value : 100,
		color : "#69D2E7"
	}			
];

var options = {
	//Boolean - Whether we should show a stroke on each segment
	segmentShowStroke : false,

	percentageInnerCutout : 80,
	
	//Boolean - Whether we should animate the chart	
	animation : true,
	
	//Number - Amount of animation steps
	animationSteps : 100,
	
	//String - Animation easing effect
	animationEasing : "easeOutBounce",
	
	//Boolean - Whether we animate the rotation of the Pie
	animateRotate : true,

	//Boolean - Whether we animate scaling the Pie from the centre
	animateScale : false,
	
	//Function - Will fire on animation completion.
	onAnimationComplete : null
}

//Get context with jQuery - using jQuery's .get() method.
var ctx = $("#chart").get(0).getContext("2d");

var test = new Chart(ctx).Doughnut(data, options);